### ISSUE TITLE
rename - copy failed

### ISSUE THREAD

**Issue by muralikodali** [nereusx/notes#1]
when renaming file, file is renamed without copying contents showing info - copy failed at bottom of screen.

An empty file is created with renamed file.

**Comment by nereusx** [comment]
There must a copy of the note in the $BACKUPDIR or whatever have you in ~/.notesrc

The copy_file() has some notes like the following printed in stderr, it would be very helpful if you copy it.
```
fprintf(stderr, "%s: errno %d: %s\n", src, errno, strerror(errno));
```

**Comment by muralikodali** [comment]
there is no copy of the note in backup directory.
i have installed notes to /home/xxxx/bin folder.
nothing is printed as stderr on screen, except copy failed.

i have attached a gif showing the error.

![Peek 2021-11-26 16-19](https://user-images.githubusercontent.com/11482766/143570076-2c03f9a4-71d4-4501-bee7-73146ad8b0d4.gif)

**Comment by nereusx** [comment]
Thank you.

fixed: I had forgot to check if the section already existed, so mkdir() hit error...  silly of me...

**Comment by muralikodali** [comment]
thanks.

rename function is working as intended.
