### ISSUE TITLE
Issues drawing box characters

### ISSUE THREAD

**Issue by JamesMConroy** [nereusx/notes#2]
When I compile and run I get a long series of `M-b~T~@` printed in place of the line separating the file info from the file contents.

Ex.

![image](https://user-images.githubusercontent.com/23198389/152626441-c4733788-39a3-42be-ae44-8241500558cb.png)

I tracked the issue down to [this line](https://github.com/nereusx/notes/blob/main/notes.c#L851). Specifically the `─` (U+2500) character.

Replacing it with a `-` resulted in a dotted line. I assume there is a similar issue with the for the status line.

Maybe I'm on an older version of ncurses that doesn't support unicode (`usr/include/ncurses.h` says it's version `v 1.269 2020/08/17`).

Simple solution is to replace those characters and recompile.

**Comment by nereusx** [comment]
It is non-utf-8 terminal. Check your locale:
```
~ > locale
LANG=el_GR.UTF-8
```
For american english, use `en_US.UTF-8` instead of `en_US`.
UTF-8 supported in text mode too, but with only 512 chars (VGA limitation).

It is depended of your distro where to set this. Check the `/etc/default/` file settings.

**Comment by JamesMConroy** [comment]
My locale is already set to en_US.UTF-8

```
~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
Running with `LANG=el_GR.UTF-8 notes` give me a bunch of  `�T~@` instead.

I only see this on my laptop running Pop!_OS (Ubuntu derivative) if that means anything.

**Comment by nereusx** [comment]
It is clear problem of terminal emulator, it does not enabled somehow to support utf-8.

I suppose that PopOS runs the gnome-terminal as default terminal:
https://unix.stackexchange.com/questions/8859/can-a-gnome-terminal-profile-use-utf-8-by-default

In case that didn;t work.

You can try unicode-rxvt package, or even st (from www.suckless.org)

`st` and `alacritty` are the most famous among the power users.
`urxvt` (unicode-rxvt) was, and still is an old standard.
`xfce4-terminal` is the easiest with menu about everything. Do not forgot to remove keys shortcuts.

**Comment by nereusx** [comment]
I could add a flag to avoid utf-8 strings, isnt too much, but better complain to distro about this. They have to support utf-8, international users have serious problems with so many tricks to support their language. I remember at least 6 prototypes for Greek language!!! `recode` utility is always in my standard setup!

**Comment by JamesMConroy** [comment]
The screen shot from above was in `alacritty`. I get the same issues from gnome terminal, `st`, `xfce4-terminal`, and `urxvt`.

I will probably open an issue in the distro's repo, but the character displays perfectly when I'm editing the source code, or viewing it with `less`.

**Comment by nereusx** [comment]
I have no idea what happens. Maybe it is the input.

```
~ > cat ~/.inputrc
set meta-flag on
set input-meta on
set convert-meta on
set output-meta on
```

Maybe the guys in distro could help us

**Comment by JamesMConroy** [comment]
Compiling with `lncursesw` fixed it on my end. I've submitted #3 to fix it.
