### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [nereusx/notes#4]
Would you like to add more error handling for return values from functions like the following?
* [fwrite](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html "Binary output") ⇒ [print_file_to](https://github.com/nereusx/notes/blob/478dd6afd1314217bac498252f5c9103b6293c12/notes.c#L649)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [nc_createpair](https://github.com/nereusx/notes/blob/8c053219e368ce5246d62a0fba3a2f8c4f74d009/nc-core.c#L33)

**Comment by nereusx** [comment]
Useless but ok, see it now...

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by nereusx** [comment]
segfault, it does it the unix itself. Now, to be truly good work the ISO C must have malloc to check for out of memory and one malloc without check for speed (lets say: __malloc()). But C designed to avoid such code that probably will never used. On the other hand in DOS it is really dangerous, but DOS and DOS-like OSes are dead.

**Comment by elfring** [comment]
:thought_balloon: It is just safer to [handle also “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it?

**Comment by nereusx** [comment]
C created to replace the Assembly, and did it well. It could be a bit better ... anyway...
Do not use C if you didn't used Assembly first, there is no meaning nor for the tool nor for you.

Use PASCAL or FORTRAN or a lot languages that created for no-system programming. Those languages catch a lot Run-Time-Errors, designed to do that.

Of course you can write code to check everything. You can create an "exception/catch" mechanism. The question is why ? btw, assert() is the correct way for C but release versions will have no assert code.
