### ISSUE TITLE
Color Customization

### ISSUE THREAD

**Issue by peterjschroeder** [nereusx/notes#5]
Would you consider adding a way to customize colors in notesrc? Status bar, selected line, and possibly the file path and headers (Name:, File:, Date:, Stat:).

**Comment by nereusx** [comment]
I ll try it, not soon. I would also separate the ncurses code since it work with VGA colors [like Borland's conio]. Now the colors are hardcoded in the main code - not in modules - but would be easy to change them if you know the VGA color codes.

**Comment by nereusx** [comment]
Oh, file path I assume that you mean to display... otherwise it is in notesrc.

**Comment by nereusx** [comment]
# On user's rc file (~/.notesrc) 
You can add the colors now. 
Still it is undocumented. I have to find what happens to background in ncurses after '\n' and write the documentation.

```
# interface
color normal 0x07
color status 0x70
color key 0x74
color select 0x70

# markdown
color text 0x07
color code 0x03
color bold 0x0f
color hide 0x08
```

**Comment by peterjschroeder** [comment]
Thank you. Would you consider allowing the color labels to also be changed? (Name:, File:, Date:, Stat:)

**Comment by nereusx** [comment]
I have already did such things, latest i used in my pathed version of jed. Just uses a text file and expands the variables with or without call the shell for import results from other commands.
Now, this is the difference between the definition Application and the Utility. I ve not intent to convert it to application.
It is clear that you have something specific in your mind, what is it?

**Comment by peterjschroeder** [comment]
nc_wprintf(w_prv, "\n**File:** $B%s$b\n" , note->file);
nc_wprintf(w_prv, "\n**Date:** $B%s$b\n", sdate(&note->st.st_mtime, buf));
nc_wprintf(w_prv, "\n**Stat:** $B%6d$b bytes, mode $B0%o$b, owner $B%d$b:$B%d$b\n",

The strings in bold are what I am referring too.

**Comment by nereusx** [comment]
Yes, you can remove $B and $b to remove it. Type `make && make install` and you finished.

The whole think is for TUI, if you need plain text you can use the CLI which is the same thing or add a user menu entry to type it; if you need to customize it, I have to add more keywords and/or use a form of text-file and replace whatever keywords to display the values [preferred because you can do more thinks for example to remove the whole header]. Already, the `color bold` in rc changes the color.

I am a bit confused about what you need.
This is just a predefined form to look nice enough for TUI.

**Comment by peterjschroeder** [comment]
I'd like to change the color of the actual words "File:", "Date:", "Stat:".

**Comment by nereusx** [comment]
$B = bold on, $b = bold off. Default color, window color, is the `color text`. The color codes are same as IBM VGA hardware attributes. You can use any escape code that you want as described on `man console_codes` by using C's format \033[nm (example \033[0m = reset colors, the \033 means the escape character)... After that recompile and install (`make && make install`).

Unfortunately I cant see the image, may I had better solution...
```
$ wget https://i.imgur.com/v1e4M5y.png
--2023-05-20 01:32:19--  https://i.imgur.com/v1e4M5y.png
Εύρεση του i.imgur.com (i.imgur.com)... 151.101.240.193
Connecting to i.imgur.com (i.imgur.com)|151.101.240.193|:443... συνδέθηκε.
Η αίτηση για HTTP στάλθηκε, αναμονή απάντησης... 429 Unknown Error
```

**Comment by nereusx** [comment]
Add this to ~/.notesrc; removes preview header
```
pvhead=off
```
